const translations = {
    fr: {
        // Welcome Screen
        welcomeSubtitle: "L'expérience musicale interactive.",
        bgMusic: "Musique de fond",
        language: "Langue",
        enter: "ENTRER",

        // Sidebar & Top Bar
        back: "Retour",
        home: "Accueil",
        notifications: "Notifications",
        albums: "Albums",
        videos: "Vidéos",
        bonus: "Bonus",
        likedTitles: "Titres Likés",
        library: "Bibliothèque",
        about: "À propos",
        about_mmg_music: "Mmg Music est un projet musical proposant des compositions de styles variés, avec des influences allant de la pop à l'électro, souvent inspirées par l'univers des jeux vidéo. Découvrez un univers riche en mélodies et en émotions.",
        about_mmg_beats: "Mmg Beats est le versant hip-hop et trap du projet. Retrouvez ici des instrumentales percutantes et des productions pour artistes, disponibles sur toutes les plateformes de streaming.",
        guide: "Guide",
        searchPlaceholder: "Titre, tag, album...",
        shop: "Boutique",
        achievements: "Succès",
        settings: "Paramètres",
        wifi: "WiFi",
        filterByTag: "Filtrer par tag",

        // Dashboard
        suggestions: "Nouveautés",
        recommendedPlaylists: "Playlists Recommandées",
        queueTitle: "En file d'attente",
        recentlyPlayed: "Récemment écouté",
        listenNow: "Écouter",
        socials: "Réseaux",

        // Player
        randomPlayback: "Lecture aléatoire",
        previous: "Précédent",
        next: "Suivant",
        repeatSong: "Répéter la chanson",
        volume: "Volume",
        likeSong: "Aimer la chanson",
        addPlaylist: "Ajout playlist",
        shareSong: "Partager la chanson",
        showHidePlayer: "Afficher/Masquer le lecteur",
        noTrackPlaying: "Aucun titre en lecture",
        autoplay: "Lecture auto",
        autoplayOn: "Lecture auto activée",
        autoplayOff: "Lecture auto désactivée",
        linkCopied: "Lien copié dans le presse-papiers !",
        copyFailed: "La copie a échoué.",

        // Cards & Sections
        titles: "Titres",
        toggleView: "Changer de vue",
        like: "Aimer",
        removeLike: "Ne plus aimer",
        removePlaylist: "Retrait playlist",
        listenToTitle: "Écouter le titre",
        viewAlbum: "Voir l'album",
        musicTitle: "Titre musical",
        videoOrMakingOf: "Vidéo / Making-of",
        viewContent: "Voir le contenu",
        workInProgress: "Contenu en préparation...",
        noResults: "Aucun résultat trouvé.",
        noLikedTitles: "Vous n'avez pas encore liké de titre.",
        playlistEmpty: "Votre playlist est vide.",
        currentPlaylist: "Ma Playlist",

        // Details Page
        album: "Album",
        year: "Année",
        inspirations: "Inspirations",
        tags: "Tags",
        listenOn: "Écouter sur",
        launchSong: "Lancer la chanson",
        addToPlaylist: "Ajout playlist",
        addedToPlaylist: "Ajouté à la playlist",
        gameplayVideo: "Vidéo Gameplay",
        makingOfVideo: "Vidéo Making-Of",
        videoClip: "Clip",
        videoMakingOf: "Making Of",
        noAssociatedVideo: "Aucune vidéo associée.",
        unknown: "Inconnu",

        // Settings & Overlays
        sfx: "Effets sonores (SFX)",
        bgPlay: "Lecture arrière-plan (stable)",
        bgPlayInfo: "Active une méthode pour empêcher la musique de se couper lorsque l'application est en arrière-plan sur mobile. Peut consommer un peu plus de batterie.",
        connecting: "Connexion...",
        connectionSuccess: "Connecté avec succès !",
        moreOptions: "Options",
        share: "Partager",
        theme: "Mode Sombre",

        // Shop & Achievements
        shopThemes: "Thèmes",
        theme_default: "Thème par Défaut",
        theme_default_desc: "Le style original et épuré de la MMGEAR.",
        theme_8bit: "Thème 8-bit",
        theme_8bit_desc: "Une interface pixelisée, comme sur les anciennes consoles.",
        theme_16bit: "Thème 16-bit",
        theme_16bit_desc: "Un style rappelant l'ère des consoles 16-bit.",
        theme_ps_style: "Thème PS Style",
        theme_ps_style_desc: "Inspiré des menus iconiques de la PlayStation.",
        theme_android: "Thème Android",
        theme_android_desc: "Un design moderne et minimaliste, style Material You.",
        theme_spotimon: "Thème Spotimon",
        theme_spotimon_desc: "Un style inspiré des jeux Pokémon sur DS.",
        shopBackgrounds: "Arrière-plans",
        bg_bubbles: "Aurore Verte",
        bg_theme_default: "Défaut",
        bg_waves: "Nuit Étoilée", // Conservé pour la compatibilité, mais peut être renommé
        bg_digital: "Digital", // NOUVEAU
        bg_blurry_gradient: "Dégradé Flou",
        bg_blob: "Blob",
        select: "Sélectionner",
        selected: "Sélectionné",
        unlock: "Débloquer",
        unlockWithLockIcon: "<i class='fas fa-lock'></i> Débloquer",
        myCoins: "Mes Pièces",
        secretCode: "Code secret...",
        shopMissions: "Missions",
        shopAndRewards: "Boutique & Succès",
        missionCompleted: "Terminé",
        activate: "Activer",
        achievementUnlocked: "Succès déverrouillé",
        allAchievementsUnlocked: "Tous les succès ont été déverrouillés !",
        allSongsUnlocked: "Tous les morceaux ont été débloqués !",
        incorrectCode: "Code incorrect.",
        achievement_loopMaster_title: "Maître de la boucle",
        confirmPurchase: "Confirmer l'achat",
        confirm: "Confirmer",
        cancel: "Annuler",
        purchaseMessage: "Voulez-vous vraiment acheter <strong>{itemName}</strong> pour {itemCost} <i class='fas fa-coins'></i> ?",
        purchaseSuccess: "Achat réussi !",
        themeUnlocked: "Thème Débloqué",
        yourCoins: "Vos pièces : {userCoins} <i class='fas fa-coins'></i>",
        notEnoughCoins: "Vous n'avez pas assez de pièces !",
        achievement_loopMaster_desc: "Écouter 3 fois de suite le même titre en boucle.",
        achievement_retroPlayer_title: "Joueur Rétro",
        achievement_retroPlayer_desc: "Écouter 3 titres de la catégorie 'Rétro'.",
        achievement_spotimonFan_title: "Fan de Spotimon",
        achievement_spotimonFan_desc: "Écouter tous les titres de la série 'Spotimon'.",
        unlockThemeMission: "Pour débloquer ce thème, terminez la mission :",
        finishMission: "Pour débloquer, terminez la mission :",
        completeMission: "Terminer la mission :",
        unlockWithCoins: "Cet article peut être acheté pour {cost} pièces.",
        unlockBackgroundWithCoins: "Vous pouvez débloquer un nouvel arrière-plan pour {cost} pièces.",
        unlockTrackWithCoins: "Vous pouvez débloquer un nouveau titre pour {COIN_COST_UNLOCK} pièces.",
        achievement_patienceIsKey_desc: "Attendre la fin de la connexion WiFi 2 fois.",
        achievement_psPlayer_title: "Joueur PlayStation",
        achievement_psPlayer_desc: "Écouter 2 titres de la catégorie 'PlayStation'.",

        // Notifications & Dialogs
        titleAddedPlaylist: "Titre ajouté à votre playlist !",
        titleRemovedPlaylist: "Titre retiré de votre playlist.",
        devMessageTitle: "Message du développeur",
        playlistCleared: "Playlist vidée.",
        playlistSaved: "Playlist sauvegardée dans la bibliothèque !",
        unlockAvailableTitle: "Déblocage disponible !",
        unlockAvailableDesc: "Vous avez assez de pièces pour débloquer un nouveau contenu exclusif.",
        updateLog: "Journal des mises à jour",
        markAsRead: "Marquer comme lu",
        trackLocked: "Ce titre est verrouillé. Débloquez-le dans la boutique d'albums !",
        youUnlocked: "Vous avez débloqué",
        allTracksUnlocked: "Tous les titres de cet album sont déjà débloqués.",
        needCoinsToUnlock: "Vous avez besoin de {COIN_COST_UNLOCK} pièces pour débloquer un titre.",
        trackToUnlock_one: "{count} titre à débloquer",
        trackToUnlock_many: "{count} titres à débloquer",

        // PWA
        pwaInstallTitle: "Installer l'application MMGEAR",
        pwaInstallDescription: "Pour une expérience optimale, installez l'application sur votre appareil. C'est rapide, léger et ne prend que peu de place.",
        pwaInstallBenefits: "Avantages :",
        pwaBenefit1: "Accès rapide et direct depuis votre écran d'accueil.",
        pwaBenefit2: "Badge de notification sur l'icône pour les nouveautés.",
        pwaBenefit3: "Interface optimisée pour une expérience mobile fluide.",
        pwaInstall: "Installer",
        pwaDismiss: "Plus tard",
        pwaInstallSuccess: "Application installée avec succès !",

        // Guide
        guideChoice: "Choisir un guide",
        guideMain: "1. Menu Principal",
        guideMusic: "2. Titres Musicaux",
        tutorial_main_1: "Ici, vous pouvez changer de profil entre 'Mmg Music' et 'Mmg Beats'.",
        tutorial_main_2: "Ces boutons vous permettent de revenir en arrière, d'aller à l'accueil ou de voir vos notifications.", // Inutilisé, mais conservé
        tutorial_main_3: "Utilisez la barre de recherche pour trouver un titre, un album ou un tag. Le bouton à droite permet de filtrer par tags.",
        tutorial_main_9: "Changez de profil ici entre 'Mmg Music' et 'Mmg Beats'.",
        tutorial_main_12: "Ceci est le lecteur principal. Il apparaît dès qu'une musique est lancée.",
        tutorial_main_13: "Cliquez sur la pochette pour voir les détails du titre ou la vidéo.",
        tutorial_main_new_1: "Bienvenue sur la MMGEAR ! Cette barre latérale est votre centre de navigation principal.",
        tutorial_main_new_2: "Le bouton 'Notifications' vous informe des nouveautés et des messages importants.",
        tutorial_main_new_3: "Naviguez entre les différentes sections du profil sélectionné.",
        tutorial_main_new_4: "Ici, vous pouvez changer le thème (clair/sombre) et accéder à ce guide à tout moment.",
        tutorial_main_new_5: "La barre du haut contient la recherche et les accès rapides aux différentes fonctions.",
        tutorial_main_new_6: "Sur ordinateur, accédez rapidement à la boutique, aux paramètres et à l'heure. Sur mobile, ces icônes sont réparties différemment.",
        tutorial_main_new_7: "Le tableau de bord vous donne un aperçu rapide de tout ce qui est important.",
        tutorial_main_new_8: "Les dernières nouveautés sont présentées dans ce carrousel. Faites-les défiler !",
        tutorial_main_new_9: "Découvrez des playlists thématiques ou consultez la file d'attente des prochains titres.",
        tutorial_main_new_10: "Retrouvez tous les réseaux sociaux ici. Cliquez pour afficher le nom d'utilisateur.",
        tutorial_main_new_11: "Contrôlez la lecture, activez le mode aléatoire ou la répétition.",
        tutorial_main_new_12: "Aimez, ajoutez à une playlist, partagez ou gérez le volume ici.",
        tutorial_main_new_13: "Cliquez sur cette poignée pour réduire ou agrandir le lecteur.",
        tutorial_music_1: "Voici une carte de titre. Un clic dessus lance la lecture.",
        tutorial_music_2: "Le cœur permet d'ajouter ce titre à vos 'Titres Likés'.",
        tutorial_music_3: "Le bouton '+' permet de l'ajouter à votre playlist personnelle. L'icône changera en '✓'.",
        tutorial_music_4: "Voici la page de détails. La pochette peut être agrandie en cliquant dessus.",
        tutorial_music_5: "Vous pouvez cliquer sur le nom de l'album ou sur les tags pour filtrer et découvrir d'autres contenus similaires.",
        tutorial_music_6: "Le bouton 'Ajouter à la playlist' est aussi disponible ici.",
        tutorial_music_7: "Retrouvez les liens pour écouter ce titre sur vos plateformes de streaming préférées.",
        tutorial_music_8: "S'il existe des vidéos associées (gameplay, making-of), elles apparaîtront ici.",
        tutorial_music_9: "Si l'autoplay est désactivé, vous pouvez lancer la lecture manuellement avec ce bouton.",
        tutorial_music_10_pc: "Ces boutons permettent de naviguer entre les titres de l'album ou de la liste actuelle sur le lecteur de bureau.",
        tutorial_music_10_mobile: "Sur le lecteur plein écran, ces boutons permettent de naviguer entre les titres.",
        tutorial_music_11: "C'est tout pour ce guide ! Vous pouvez maintenant explorer le reste du site.",
        // NOUVEAU: Guide Ordinateur
        "tutorial_computer_1": "Bienvenue ! La barre latérale est votre centre de navigation principal.",
        "tutorial_computer_2": "Utilisez ces boutons pour revenir en arrière, retourner à l'accueil ou voir vos notifications (mises à jour, déblocages disponibles...).",
        "tutorial_computer_3": "Basculez entre les deux profils d'artiste : Mmg Music (musiques variées) et Mmg Beats (prods hip-hop).",
        "tutorial_computer_4": "Naviguez entre les différentes sections du profil sélectionné.",
        "tutorial_computer_5": "Ici, vous pouvez changer le thème de l'interface (clair/sombre).",
        "tutorial_computer_6": "La barre du haut contient la recherche et un accès rapide à diverses fonctions.",
        "tutorial_computer_7": "Utilisez la barre de recherche pour trouver un titre, un album ou un tag. Le bouton à droite permet de filtrer par tags.",
        "tutorial_computer_8": "Accédez rapidement aux settings où on peut régler la musique de fond et les SFX, l'affichage du contenu en mode grille ou liste, et la langue du site, ainsi que le wifi (petit easter egg !)",
        "tutorial_computer_9": "Les dernières sorties sont mises en avant dans ce carrousel. Faites-les défiler !",
        "tutorial_computer_10": "Découvrez des playlists thématiques. Un clic dessus les enregistre directement dans votre bibliothèque.",
        "tutorial_computer_11": "Retrouvez ici les titres récemment écoutés, pour ne jamais perdre le fil de vos découvertes.",
        "tutorial_computer_12": "Retrouvez ici les liens vers les réseaux sociaux du profil sélectionné.",
        "tutorial_computer_13": "Ceci est le lecteur principal. Cliquez sur la pochette pour voir les détails du titre (musique) ou pour revenir à la vidéo (vidéo).",
        "tutorial_computer_14": "Contrôlez la lecture, activez le mode aléatoire ou la répétition.",
        "tutorial_computer_15": "Aimez, ajoutez à une playlist, share, ou gérez le volume ici.",
        // NOUVEAU: Guide Mobile
        "tutorial_mobile_1": "Bienvenue dans le guide du menu principal de la Mmgear ! Sont présentés le bouton notifs (mises à jour, déblocages...), le bouton recherche qui affiche la barre de recherche et les tags, et les settings où l'on peut régler la musique, les SFX, l'affichage, la langue, et trouver un easter egg (wifi !).",
        "tutorial_mobile_2": "Basculez ici entre les deux profils d'artiste : Mmg Music (musiques variées) et Mmg Beats (prods hip-hop).",
        "tutorial_mobile_3": "Utilisez la barre de recherche pour trouver un titre ou un album. Le bouton tag permet un filtrage avancé.",
        "tutorial_mobile_4": "Les dernières sorties sont mises en avant dans ce carrousel. Faites-les défiler !",
        "tutorial_mobile_5": "Découvrez des playlists thématiques créées spécialement pour vous. Un appui dessus les enregistre directement dans votre bibliothèque pour une écoute ultérieure.",
        "tutorial_mobile_6": "Retrouvez ici les titres que vous avez récemment écoutés, pour ne jamais perdre le fil de vos découvertes.",
        "tutorial_mobile_7": "Retrouvez ici les liens vers les réseaux sociaux du profil sélectionné.",
        "tutorial_mobile_8": "Cette section vous permet de (re)lancer les guides pour découvrir toutes les fonctionnalités de l'application.",
        "tutorial_mobile_9": "Une petite section pour en savoir plus sur le profil d'artiste actuellement sélectionné.",
        "tutorial_mobile_10": "Utilisez la barre de navigation pour explorer les différentes sections : Accueil, Albums, Vidéos, Boutique et votre Bibliothèque personnelle.",

        // Playlist & Queue
        playPlaylist: "Lancer la playlist",
        savePlaylist: "Enregistrer la playlist",
        clearPlaylist: "Vider la playlist",
        deleteFromPlaylist: "Supprimer de la playlist",
        playNext: "Lancer ensuite",
        queue: "File d'attente",
        viewMore: "Voir plus",
        addedToQueue: "ajouté à la file d'attente",
        addToQueue: "Ajout file d'attente",
        removeFromQueue: "Retirer de la file d'attente",
        fromTitles: "depuis titres",
        fromMyPlaylist: "depuis ma playlist",
        fromPlaybackQueue: "depuis liste de lecture",
        fromLiked: "depuis les likes",
        fromVideos: "depuis vidéos",
        fromMmgPlaylists: "depuis Mmg Playlists",
        queueEmpty: "File d'attente vide. Clic droit (PC) ou appui long (mobile) pour ajouter.",
        nowPlayingFrom: "Lecture en cours depuis :",

        // Search & Filter
        searchFor: "Recherche pour",
        contentWithTag: "Contenu avec le tag",
        searchResults: "Résultats de recherche",

        // Nouveaux ajouts
        listView: "Affichage",
        grid: "Grille",
        list: "Liste",
        instrumentals: "Instrumentales",
        titleAndArtist: "Titre & Artiste",
        fullscreen: "Plein écran",

        // Track Descriptions (FR)
        trackDescriptions: {
            "title7": "Une composition pop inspirée des récents jeux Pokémon, mais avec une touche qui la rapproche des thèmes d'animé japonais. L'instrumentation organique évoque une scène romantique de fin d'épisode ou une nuit tranquille au bord d'un lac. Finalement, elle aurait toute sa place dans une série animée Pokémon !",
            "title1": "Inspiré par les thèmes joyeux et entraînants des jeux de sport Nintendo, en particulier Wii Sports. Composé comme une boucle infinie, ce titre utilise les éléments typiques du genre : batterie calme, mélodie au piano, marimba et les voix iconiques \"dooh\" présentes dans de nombreux titres Nintendo !",
            "title2": "Une ambiance de plage ensoleillée avec des percussions latines. Cette chanson est composée d'une partie A et d'une partie B, la section B comportant un petit solo.",
            "title3": "Évoque le son des menus et des écrans de connexion du début des années 2000. Une composition de style Frutiger Aero, avec des effets sonores qui rappellent particulièrement les longs temps de chargement sur les vieilles consoles !",
            "title4": "Un thème de boutique classique, parfait pour le shopping virtuel. L'instrumentation et la composition sont inspirées du thème de la chaîne boutique Wii !",
            "title5": "Une composition orientée pop, un peu éloignée d'Animal Crossing, mais évoquant une ambiance de soirée d'été. La guitare principale et la batterie organique donnent un ton naturel. La mélodie est complétée par un pluck avec beaucoup de réverbération, créant l'atmosphère chaleureuse du morceau.",
            "title6": "Cette composition rappelle l'univers magique des jeux Zelda. La mélodie légèrement mystérieuse et joyeuse est composée d'une ligne de basse envoûtante, avec des éléments ajoutés comme des synthés et des pads. On a l'impression d'explorer une forêt en Hyrule !",
            "title8": "Une composition Frutiger Aero avec un piano néo-soul. Au fur et à mesure que le morceau progresse, la sensation organique des instruments se transforme en un son numérique, avec divers synthés remplaçant le piano !",
            "title9": "Combien de jeux PS1, PS2 et autres de cette époque utilisent des morceaux DnB, en particulier pour les jeux de course ? Un vrai jeu old-school doit inclure ce genre de musique au moins une fois dans son OST. Inspiré par Ridge Racer et d'autres, ce titre est un hommage aux jeux de course vintage.",
            "title10": "Mon interprétation de la Route Arc-en-ciel de la Wii. Tous les éléments de la bande originale de Mario Kart Wii sont là : une ligne de basse similaire au menu, le piano comme mélodie principale, et des synthés, cuivres et guitare pour pimenter la composition. Le morceau inclut aussi la fanfare de départ, le bruit du moteur avant le départ, les sons de tour, la musique accélérée au dernier tour et la musique du classement final !",
            "title11": "En tant que grand fan des jeux Donkey Kong et de David Wise, cet hommage était essentiel. Utilisant les mêmes instruments et bibliothèques musicales que D. Wise, en particulier ceux de Donkey Kong Country Returns et Tropical Freeze, ce titre a une atmosphère plus joyeuse, style calypso, que l'OST originale. Il colle bien à l'image et rend hommage tout en ajoutant une touche personnelle ! On s'imagine facilement jouer DK sur une plage tropicale.",
            "title12": "Les jeux Pokémon, en particulier les 3e et 4e générations, sont un souvenir d'enfance précieux. Pour rendre hommage à la 4e génération, j'ai composé un titre de style latin qui ressemble beaucoup à la musique de cette époque. J'ai utilisé presque les mêmes instruments que le jeu pour donner à la composition cette sensation originale de Nintendo DS. De nombreux instruments \"conversent\" entre eux, ce qui est typique des thèmes de ville Pokémon comme Féli-Cité ! Ce titre est plus ensoleillé, et on peut l'imaginer comme un thème alternatif pour Rivamar. Suivant la tradition Pokémon, j'ai aussi créé un remake moderne, intitulé \"Spotimon (Radiant Jade Version)\".",
            "title13": "C'est la version modernisée et remasterisée de \"Spotimon (Jade Version)\", avec des instruments plus réalistes par rapport aux soundfonts DS originaux ! On imagine facilement ce remake sur la Switch.",
            "title14": "Un morceau DnB typique de l'ère des jeux de course PS1/PS2. La mélodie principale riche en synthés le fait ressembler davantage à un jeu futuriste qu'à un titre de course classique. Le rythme de percussion fort et frénétique est idéal pour un jeu de course spatial ! La sensation spatiale et flottante du morceau est transmise par des pads très réverbérés et éthérés.",
            "title15": "Un titre conçu pour évoquer une atmosphère mystérieuse et légèrement effrayante, parfait pour un manoir hanté ou un niveau effrayant dans un jeu vidéo.",
            "title16": "Un morceau DnB créé avec des instruments organiques, servant de transition entre les anciens jeux de course qui utilisaient la DnB et les titres récents avec instrumentation live, comme Mario Kart 8 et World, qui ont été enregistrés avec des tonnes de musiciens ! Cette chanson est aussi conçue comme une boucle infinie avec différentes parties et a une sensation jazz-fusion distincte, inspirée par Mario Kart et d'autres artistes.",
            "title17": "Les valses sont un choix populaire pour les thèmes sous-marins dans les jeux Nintendo, en particulier dans les titres Mario et Pokémon. Cette valse rend hommage à tous ces thèmes sous-marins, en particulier ceux de Mario sur Wii. Pour renforcer l'immersion, des bruits de vagues ont été ajoutés ! La composition est une boucle infinie avec deux parties qui s'enchaînent parfaitement.",
            "title18": "Un titre avec une sensation jazzy, mystérieuse et cinématographique, installant une atmosphère calme et frissonnante.",
            "title19": "Une pièce cinématographique infusée de jazz qui crée une ambiance mystérieuse et sombre.",
            "title20": "Un titre cinématographique atmosphérique et chill, parfait pour une conduite nocturne ou une scène d'évasion mystérieuse.",
            "title21": "Un titre cool, jazzy et cinématographique mettant en vedette un piano Rhodes et des mélodies de synthé ressemblant à des sirènes, créant une ambiance mystérieuse mais détendue.",
            "ds-track1": "Premier extrait exclusif de Dream Season.",
            "ds-track2": "Deuxième extrait exclusif.",
            "ds-track3": "Troisième extrait exclusif.",
            "title22": "Un thème désertique pour une aventure ensoleillée.",
            "title23": "La suite de la course, encore plus endiablée.",
            "title24": "Ambiance western sur la côte ouest.",
            "title25": "Dévalez les pentes enneigées avec ce titre.",
            "title26": "Une version alternative et nostalgique.",
            "title27": "Un thème de combat épique.",
            "title28": "Explorez les profondeurs avec ce thème aquatique.",
            "title29": "Un thème mystérieux pour les grottes sombres.",
            "title30": "Une composition frutiger aero qui rappelle les morceaux de menus dans les consoles de 7è génération. Celle-ci intègre des instruments synthétiques et organiques (au timbre volontairement artificiel), comme un mélange du futur optimiste envisagé par le mouvement frutiger aero, avec les éléments organiques représentant le présent.",
            "beat1": "Une prod trap puissante dans le style de Zaytoven."
        }
    },
    en: {
        // Welcome Screen
        welcomeSubtitle: "The interactive music experience.",
        bgMusic: "Background Music",
        language: "Language",
        enter: "ENTER",

        // Sidebar & Top Bar
        back: "Back",
        home: "Home",
        notifications: "Notifications",
        albums: "Albums",
        videos: "Videos",
        bonus: "Bonus",
        likedTitles: "Liked Titles",
        library: "Library",
        about: "About",
        about_mmg_music: "Mmg Music is a musical project offering compositions in various styles, with influences ranging from pop to electronic music, often inspired by the world of video games. Discover a universe rich in melodies and emotions.",
        about_mmg_beats: "Mmg Beats is the hip-hop and trap side of the project. Find hard-hitting instrumentals and productions for artists here, available on all streaming platforms.",
        guide: "Guide",
        searchPlaceholder: "Title, tag, album...",
        shop: "Shop",
        achievements: "Achievements",
        settings: "Settings",
        wifi: "WiFi",
        filterByTag: "Filter by Tag",

        // Dashboard
        suggestions: "What's New",
        recommendedPlaylists: "Recommended Playlists",
        queueTitle: "Playback Queue",
        recentlyPlayed: "Recently Played",
        listenNow: "Listen",
        socials: "Socials",

        // Player
        randomPlayback: "Shuffle",
        previous: "Previous",
        next: "Next",
        repeatSong: "Repeat Song",
        volume: "Volume",
        likeSong: "Like Song",
        addPlaylist: "Add to Playlist",
        shareSong: "Share Song",
        showHidePlayer: "Show/Hide Player",
        noTrackPlaying: "No track playing",
        autoplay: "Autoplay",
        autoplayOn: "Autoplay enabled",
        autoplayOff: "Autoplay disabled",
        linkCopied: "Link copied to clipboard!",
        copyFailed: "Copy failed.",

        // Cards & Sections
        titles: "Tracks",
        toggleView: "Toggle View",
        like: "Like",
        removeLike: "Unlike",
        removePlaylist: "Remove from playlist",
        listenToTitle: "Listen to the track",
        viewAlbum: "View album",
        musicTitle: "Music Track",
        videoOrMakingOf: "Video / Making-Of",
        viewContent: "View content",
        workInProgress: "Content in preparation...",
        noResults: "No results found.",
        noLikedTitles: "You haven't liked any tracks yet.",
        playlistEmpty: "Your playlist is empty.",
        currentPlaylist: "My Playlist",

        // Details Page
        album: "Album",
        year: "Year",
        inspirations: "Inspirations",
        tags: "Tags",
        listenOn: "Listen on",
        launchSong: "Play Song",
        addToPlaylist: "Add to Playlist",
        addedToPlaylist: "Added to Playlist",
        gameplayVideo: "Gameplay Video",
        makingOfVideo: "Making-Of Video",
        videoClip: "Music Video",
        videoMakingOf: "Making Of",
        noAssociatedVideo: "No associated video.",
        unknown: "Unknown",

        // Settings & Overlays
        sfx: "Sound Effects (SFX)",
        bgPlay: "Background Play (stable)",
        bgPlayInfo: "Enables a method to prevent music from stopping when the app is in the background on mobile. May consume slightly more battery.",
        connecting: "Connecting...",
        connectionSuccess: "Successfully connected!",
        moreOptions: "Options",
        share: "Share",
        theme: "Dark Mode",

        // Shop & Achievements
        shopThemes: "Themes",
        theme_default: "Default Theme",
        theme_default_desc: "The original and clean style of the MMGEAR.",
        theme_8bit: "8-bit Theme",
        theme_8bit_desc: "A pixelated interface, just like on old consoles.",
        theme_16bit: "16-bit Theme",
        theme_16bit_desc: "A style reminiscent of the 16-bit console era.",
        theme_ps_style: "PS Style Theme",
        theme_ps_style_desc: "Inspired by the iconic PlayStation menus.",
        theme_android: "Android Theme",
        theme_android_desc: "A modern and minimalist design, Material You style.",
        theme_spotimon: "Spotimon Theme",
        theme_spotimon_desc: "A style inspired by the DS Pokémon games.",
        shopBackgrounds: "Backgrounds",
        bg_bubbles: "Green Dawn",
        bg_theme_default: "Default",
        bg_waves: "Starry Night", // Kept for compatibility, can be renamed
        bg_digital: "Digital", // NEW
        bg_blurry_gradient: "Blurry Gradient",
        bg_blob: "Blob",
        select: "Select",
        selected: "Selected",
        unlock: "Unlock",
        unlockWithLockIcon: "<i class='fas fa-lock'></i> Unlock",
        myCoins: "My Coins",
        secretCode: "Secret code...",
        shopMissions: "Missions",
        shopAndRewards: "Shop & Rewards",
        missionCompleted: "Completed",
        activate: "Activate",
        achievementUnlocked: "Achievement Unlocked",
        allAchievementsUnlocked: "All achievements have been unlocked!",
        allSongsUnlocked: "All songs have been unlocked!",
        incorrectCode: "Incorrect code.",
        achievement_loopMaster_title: "Loop Master",
        confirmPurchase: "Confirm Purchase",
        confirm: "Confirm",
        cancel: "Cancel",
        purchaseMessage: "Do you really want to buy <strong>{itemName}</strong> for {itemCost} <i class='fas fa-coins'></i>?",
        purchaseSuccess: "Purchase successful!",
        themeUnlocked: "Unlocked",
        yourCoins: "Your coins: {userCoins} <i class='fas fa-coins'></i>",
        notEnoughCoins: "You don't have enough coins!",
        achievement_loopMaster_desc: "Listen to the same track 3 times in a row on loop.",
        achievement_retroPlayer_title: "Retro Player",
        achievement_retroPlayer_desc: "Listen to 3 tracks from the 'Retro' category.",
        achievement_spotimonFan_title: "Spotimon Fan",
        achievement_spotimonFan_desc: "Listen to all tracks from the 'Spotimon' series.",
        unlockThemeMission: "To unlock this theme, complete the mission:",
        finishMission: "To unlock, complete the mission:",
        completeMission: "Complete mission:",
        unlockWithCoins: "This item can be purchased for {cost} coins.",
        unlockBackgroundWithCoins: "You can unlock a new background for {cost} coins.",
        unlockTrackWithCoins: "You can unlock a new track for {COIN_COST_UNLOCK} coins.",
        achievement_patienceIsKey_desc: "Wait for the WiFi connection to finish 2 times.",
        achievement_psPlayer_title: "PlayStation Player",
        achievement_psPlayer_desc: "Listen to 2 tracks from the 'PlayStation' category.",

        // Notifications & Dialogs
        titleAddedPlaylist: "Track added to your playlist!",
        titleRemovedPlaylist: "Track removed from your playlist.",
        devMessageTitle: "Message from the developer",
        playlistCleared: "Playlist cleared.",
        playlistSaved: "Playlist saved to library!",
        unlockAvailableTitle: "Unlock Available!",
        unlockAvailableDesc: "You have enough coins to unlock new exclusive content.",
        updateLog: "Update Log",
        markAsRead: "Mark as read",
        trackLocked: "This track is locked. Unlock it in the album shop!",
        youUnlocked: "You unlocked",
        allTracksUnlocked: "All tracks in this album are already unlocked.",
        needCoinsToUnlock: "You need {COIN_COST_UNLOCK} coins to unlock a track.",
        trackToUnlock_one: "{count} track to unlock",
        trackToUnlock_many: "{count} tracks to unlock",

        // PWA
        pwaInstallTitle: "Install MMGEAR App",
        pwaInstallDescription: "For the best experience, install the app on your device. It's fast, lightweight, and takes up very little space.",
        pwaInstallBenefits: "Benefits:",
        pwaBenefit1: "Faster and more direct access from your home screen.",
        pwaBenefit2: "Notification badge on the icon for new releases.",
        pwaBenefit3: "Optimized interface for a smooth mobile experience.",
        pwaInstall: "Install",
        pwaDismiss: "Later",
        pwaInstallSuccess: "App installed successfully!",

        // Guide
        guideChoice: "Choose a guide",
        guideMain: "1. Main Menu",
        guideMusic: "2. Music Tracks",
        tutorial_main_1: "Here, you can switch profiles between 'Mmg Music' and 'Mmg Beats'.",
        tutorial_main_2: "These buttons allow you to go back, go home, or see your notifications.", // Unused, but kept
        tutorial_main_3: "Use the search bar to find a track, album, or tag. The button on the right allows filtering by tags.",
        tutorial_main_9: "Switch profiles here between 'Mmg Music' and 'Mmg Beats'.",
        tutorial_main_12: "This is the main player. It appears as soon as music is playing.",
        tutorial_main_13: "Click on the cover art to see the track details or the video.",
        tutorial_main_new_1: "Welcome to MMGEAR! This sidebar is your main navigation hub.",
        tutorial_main_new_2: "The 'Notifications' button informs you of new items and important messages.",
        tutorial_main_new_3: "Navigate between the different sections of the selected profile.",
        tutorial_main_new_4: "Here, you can change the theme (light/dark) and access this guide at any time.",
        tutorial_main_new_5: "The top bar contains the search and quick access to various functions.",
        tutorial_main_new_6: "On desktop, quickly access the shop, settings, and the time. On mobile, these icons are arranged differently.",
        tutorial_main_new_7: "The dashboard gives you a quick overview of everything important.",
        tutorial_main_new_8: "The latest releases are featured in this carousel. Scroll through them!",
        tutorial_main_new_9: "Discover themed playlists or check the queue for upcoming tracks.",
        tutorial_main_new_10: "Find all social media links here. Click to display the username.",
        tutorial_main_new_11: "Control playback, enable shuffle mode, or repeat.",
        tutorial_main_new_12: "Like, add to a playlist, share, or manage the volume here.",
        tutorial_main_new_13: "Click this handle to minimize or maximize the player.",
        tutorial_music_1: "This is a track card. Clicking it starts playback.",
        tutorial_music_2: "The heart icon lets you add this track to your 'Liked Tracks'.",
        tutorial_music_3: "The '+' button adds it to your personal playlist. The icon will change to a '✓'.",
        tutorial_music_4: "This is the details page. The cover art can be enlarged by clicking on it.",
        tutorial_music_5: "You can click on the album name or tags to filter and discover other similar content.",
        tutorial_music_6: "The 'Add to Playlist' button is also available here.",
        tutorial_music_7: "Find the links to listen to this track on your favorite streaming platforms.",
        tutorial_music_8: "If there are associated videos (gameplay, making-of), they will appear here.",
        tutorial_music_9: "If autoplay is disabled, you can start playback manually with this button.",
        tutorial_music_10_pc: "Use these buttons to navigate between tracks in the current album or list on the desktop player.",
        tutorial_music_10_mobile: "On the full-screen player, use these buttons to navigate between tracks.",
        tutorial_music_11: "That's all for this guide! You can now explore the rest of the site.",
        // NEW: Computer Guide
        "tutorial_computer_1": "Welcome! The sidebar is your main navigation hub.",
        "tutorial_computer_2": "Use these buttons to go back, return to the main menu, or check your notifications (updates, available unlocks...).",
        "tutorial_computer_3": "Switch between the two artist profiles: Mmg Music (varied music) and Mmg Beats (hip-hop instrumentals).",
        "tutorial_computer_4": "Navigate between the different sections of the selected profile.",
        "tutorial_computer_5": "Here, you can change the interface theme (light/dark).",
        "tutorial_computer_6": "The top bar contains the search and quick access to various functions.",
        "tutorial_computer_7": "Use the search bar to find a track, album, or tag. The button on the right allows filtering by tags.",
        "tutorial_computer_8": "Quickly access the settings where you can adjust background music and SFX, switch between grid/list view, change the site language, and find the wifi easter egg!",
        "tutorial_computer_9": "The latest releases are featured in this carousel. Scroll through them!",
        "tutorial_computer_10": "Discover themed playlists. Clicking on one saves it directly to your library.",
        "tutorial_computer_11": "Find your recently played tracks here, so you never lose track of your discoveries.",
        "tutorial_computer_12": "Find links to the selected profile's social media here.",
        "tutorial_computer_13": "This is the main player. Click on the cover art to see the track details (music) or to return to the video (video).",
        "tutorial_computer_14": "Control playback, enable shuffle mode, or repeat.",
        "tutorial_computer_15": "Like, add to a playlist, share, or manage the volume here.",
        // NEW: Mobile Guide
        "tutorial_mobile_1": "Welcome to the MMGEAR main menu guide! It introduces the notifs button (updates, unlocks...), the search button that shows the search bar and tags, and the settings where you can adjust music, SFX, display, language, and find a wifi easter egg!",
        "tutorial_mobile_2": "Switch here between the two artist profiles: Mmg Music (varied music) and Mmg Beats (hip-hop instrumentals).",
        "tutorial_mobile_3": "Use the search bar to find a track or album. The tag button allows for advanced filtering.",
        "tutorial_mobile_4": "The latest releases are featured in this carousel. Scroll through them!",
        "tutorial_mobile_5": "Discover themed playlists created just for you. Tapping on one saves it directly to your library for later listening.",
        "tutorial_mobile_6": "Find your recently played tracks here, so you never lose track of your discoveries.",
        "tutorial_mobile_7": "Find links to the selected profile's social media here.",
        "tutorial_mobile_8": "This section allows you to (re)launch the guides to discover all the application's features.",
        "tutorial_mobile_9": "A small section to learn more about the currently selected artist profile.",
        "tutorial_mobile_10": "Use the navigation bar to explore the different sections: Home, Albums, Videos, Shop, and your personal Library.",

        // Playlist & Queue
        playPlaylist: "Play Playlist",
        savePlaylist: "Save Playlist",
        clearPlaylist: "Clear Playlist",
        deleteFromPlaylist: "Delete from playlist",
        playNext: "Play Next",
        queue: "Queue",
        viewMore: "View more",
        addedToQueue: "added to the queue",
        addToQueue: "Add to Queue",
        removeFromQueue: "Remove from queue",
        fromTitles: "from tracks",
        fromMyPlaylist: "from my playlist",
        fromPlaybackQueue: "from queue",
        fromLiked: "from liked songs",
        fromVideos: "from videos",
        fromMmgPlaylists: "from Mmg Playlists",
        queueEmpty: "Queue empty. Right-click (PC) or long-press (mobile) to add.",
        nowPlayingFrom: "Now playing from:",

        // Search & Filter
        searchFor: "Search for",
        contentWithTag: "Content with tag",
        searchResults: "Search Results",

        // New additions
        listView: "Display",
        grid: "Grid",
        list: "List",
        instrumentals: "Instrumentals",
        titleAndArtist: "Title & Artist",
        fullscreen: "Fullscreen",

        // Track Descriptions (EN) - Should match data.json
        trackDescriptions: {
            "title7": "A pop composition inspired by recent Pokémon games, but with a touch that brings it closer to Japanese anime themes. The organic instrumentation evokes a romantic end-of-episode scene or a quiet night by a lake. Ultimately, it would fit perfectly in a Pokémon animated series!",
            "title1": "Inspired by the cheerful and catchy themes of Nintendo sports games, especially Wii Sports. Composed as an infinite loop, this track uses typical elements of the genre: calm drums, a piano melody, a marimba, and the iconic \"dooh\" voices found in many Nintendo titles!",
            "title2": "A sunny beach atmosphere with Latin percussion. This song is composed of a Part A and a Part B, with the B section featuring a small solo.",
            "title3": "Evokes the sound of menus and connection screens from the early 2000s. A Frutiger Aero-style composition, with sound effects that particularly recall the long loading times on old consoles!",
            "title4": "A classic shop theme, perfect for virtual shopping. The instrumentation and composition are inspired by the Wii eShop theme!",
            "title5": "A pop-oriented composition, a bit distant from Animal Crossing, but evoking a summer evening vibe. The main guitar and organic drums set a natural tone. The melody is completed by a heavily reverberated pluck, creating the track's warm atmosphere.",
            "title6": "This composition is reminiscent of the magical universe of Zelda games. The slightly mysterious and cheerful melody is composed of an enchanting bassline, with added elements like synths and pads. It feels like exploring a forest in Hyrule!",
            "title8": "A Frutiger Aero composition with a neo-soul piano. As the track progresses, the organic feel of the instruments transforms into a digital sound, with various synths replacing the piano!",
            "title9": "How many PS1, PS2, and other games from that era use DnB tracks, especially for racing games? A true old-school game must include this kind of music at least once in its OST. Inspired by Ridge Racer and others, this track is a tribute to vintage racing games.",
            "title10": "My interpretation of Wii's Rainbow Road. All the elements of the Mario Kart Wii soundtrack are here: a bassline similar to the menu, the piano as the main melody, and synths, brass, and guitar to spice up the composition. The track also includes the race start fanfare, the sound of the engine revving before the start, the lap sounds, the accelerated music on the final lap, and the final ranking music!",
            "title11": "As a big fan of Donkey Kong games and David Wise, this tribute was essential. Using the same instruments and music libraries as D. Wise, particularly those from Donkey Kong Country Returns and Tropical Freeze, this track has a more cheerful, calypso-style atmosphere than the original OST. It fits the image well and pays homage while adding a personal touch! You can easily imagine playing as DK on a tropical beach.",
            "title12": "Pokémon games, especially the 3rd and 4th generations, are a cherished childhood memory. To pay tribute to the 4th generation, I composed a Latin-style track that closely resembles the music from that era. I used almost the same instruments as the game to give the composition that original Nintendo DS feel. Many instruments \"converse\" with each other, which is typical of Pokémon city themes like Jubilife City! This track is sunnier, and you can imagine it as an alternative theme for Sunyshore City. Following the Pokémon tradition, I also created a modern remake, titled \"Spotimon (Radiant Jade Version)\".",
            "title13": "This is the modernized, remastered version of \"Spotimon (Jade Version),\" featuring more realistic instruments compared to the original DS soundfonts! You can easily imagine this remake on the Switch.",
            "title14": "A typical DnB track from the PS1/PS2 racing game era. The synth-heavy main melody makes it feel more like a futuristic game than a classic racing title. The strong and frantic percussion rhythm is ideal for a space racing game! The track's spacey, floating feel is conveyed through heavily reverberated and ethereal pads.",
            "title15": "A track designed to evoke a mysterious and slightly eerie atmosphere, perfect for a haunted mansion or a spooky level in a video game.",
            "title16": "A DnB track created with organic instruments, serving as a transition between older racing games that used DnB and recent titles with live instrumentation, like Mario Kart 8 and World, which were recorded with tons of musicians! This song is also designed as an infinite loop with different parts and has a distinct jazz-fusion feel, inspired by Mario Kart and other artists.",
            "title17": "Waltzes are a popular choice for underwater themes in Nintendo games, especially in Mario and Pokémon titles. This waltz pays homage to all those underwater themes, particularly the ones from Mario on the Wii. To enhance immersion, wave sounds have been added! The composition is an infinite loop with two parts that flow seamlessly into each other.",
            "title18": "A track with a jazzy, mysterious, and cinematic feel, setting a calm and chilling atmosphere.",
            "title19": "A jazz-infused cinematic piece that creates a mysterious and dark mood.",
            "title20": "An atmospheric and chill cinematic track perfect for a late-night drive or a mysterious getaway scene.",
            "title21": "A cool, jazzy, and cinematic track featuring Rhodes piano and siren-like synth melodies, creating a mysterious yet chill vibe.",
            "ds-track1": "First exclusive preview of Dream Season.",
            "ds-track2": "Second exclusive preview.",
            "ds-track3": "Third exclusive preview.",
            "title22": "A desert theme for a sunny adventure.",
            "title23": "The sequel to the race, even more frantic.",
            "title24": "Western atmosphere on the west coast.",
            "title25": "Hit the snowy slopes with this track.",
            "title26": "An alternative and nostalgic version.",
            "title27": "An epic battle theme.",
            "title28": "Explore the depths with this aquatic theme.",
            "title29": "A mysterious theme for dark caves.",
            "title30": "A Frutiger Aero composition reminiscent of menu tracks from 7th generation consoles. It incorporates both synthetic and organic instruments (with a deliberately artificial timbre), like a blend of the optimistic future envisioned by the Frutiger Aero movement with organic elements representing the present.",
            "beat1": "A powerful trap production in the style of Zaytoven."
        }
    }
};
