const translations = {
    fr: {
        // Welcome Screen
        welcomeSubtitle: "L'expérience musicale interactive.",
        bgMusic: "Musique de fond",
        language: "Langue",
        enter: "ENTRER",

        // Sidebar & Top Bar
        back: "Retour",
        home: "Accueil",
        notifications: "Notifications",
        albums: "Albums",
        videos: "Vidéos",
        bonus: "Bonus",
        likedTitles: "Titres Likés",
        library: "Bibliothèque",
        about: "À propos",
        about_mmg_music: "Mmg Music est un projet musical axé sur la composition de bandes originales inspirées des jeux vidéo, avec des influences allant de la pop à l'électro. Découvrez un univers riche en mélodies et en émotions.",
        about_mmg_beats: "Mmg Beats est le versant hip-hop et trap du projet. Retrouvez ici des instrumentales percutantes et des productions pour artistes, disponibles sur toutes les plateformes de streaming.",
        guide: "Guide",
        searchPlaceholder: "Titre, tag, album...",
        shop: "Boutique",
        achievements: "Succès",
        settings: "Paramètres",
        wifi: "WiFi",
        filterByTag: "Filtrer par tag",

        // Dashboard
        suggestions: "Nouveautés",
        recommendedPlaylists: "Playlists Recommandées",
        queueTitle: "En file d'attente",
        listenNow: "Écouter",
        socials: "Réseaux",

        // Player
        randomPlayback: "Lecture aléatoire",
        previous: "Précédent",
        next: "Suivant",
        repeatSong: "Répéter la chanson",
        volume: "Volume",
        likeSong: "Aimer la chanson",
        addPlaylist: "Ajouter à la playlist",
        shareSong: "Partager la chanson",
        showHidePlayer: "Afficher/Masquer le lecteur",
        noTrackPlaying: "Aucun titre en lecture",
        autoplay: "Lecture auto",
        autoplayOn: "Lecture auto activée",
        autoplayOff: "Lecture auto désactivée",
        linkCopied: "Lien copié dans le presse-papiers !",
        copyFailed: "La copie a échoué.",

        // Cards & Sections
        titles: "Titres",
        toggleView: "Changer de vue",
        like: "Aimer",
        removePlaylist: "Retirer de la playlist",
        listenToTitle: "Écouter le titre",
        viewAlbum: "Voir l'album",
        musicTitle: "Titre musical",
        videoOrMakingOf: "Vidéo / Making-of",
        viewContent: "Voir le contenu",
        workInProgress: "Contenu en préparation...",
        noResults: "Aucun résultat trouvé.",
        noLikedTitles: "Vous n'avez pas encore liké de titre.",
        playlistEmpty: "Votre playlist est vide.",
        currentPlaylist: "Ma Playlist",

        // Details Page
        album: "Album",
        year: "Année",
        inspirations: "Inspirations",
        tags: "Tags",
        listenOn: "Écouter sur",
        launchSong: "Lancer la chanson",
        addToPlaylist: "Ajouter à la playlist",
        addedToPlaylist: "Ajouté à la playlist",
        gameplayVideo: "Vidéo Gameplay",
        makingOfVideo: "Vidéo Making-Of",
        noAssociatedVideo: "Aucune vidéo associée.",
        unknown: "Inconnu",

        // Settings & Overlays
        sfx: "Effets sonores (SFX)",
        bgPlay: "Lecture arrière-plan (stable)",
        bgPlayInfo: "Active une méthode pour empêcher la musique de se couper lorsque l'application est en arrière-plan sur mobile. Peut consommer un peu plus de batterie.",
        connecting: "Connexion...",
        connectionSuccess: "Connecté avec succès !",
        moreOptions: "Options",
        share: "Partager",

        // Shop & Achievements
        shopThemes: "Thèmes",
        theme_default: "Thème par Défaut",
        theme_default_desc: "Le style original et épuré de la MMGEAR.",
        theme_8bit: "Thème 8-bit",
        theme_8bit_desc: "Une interface pixelisée, comme sur les anciennes consoles.",
        theme_16bit: "Thème 16-bit",
        theme_16bit_desc: "Un style rappelant l'ère des consoles 16-bit.",
        theme_ps_style: "Thème PS Style",
        theme_ps_style_desc: "Inspiré des menus iconiques de la PlayStation.",
        theme_android: "Thème Android",
        theme_android_desc: "Un design moderne et minimaliste, style Material You.",
        shopBackgrounds: "Arrière-plans",
        bg_bubbles: "Bulles Animées",
        bg_waves: "Vagues Colorées",
        bg_gray: "Gris Simple",
        select: "Sélectionner",
        selected: "Sélectionné",
        unlock: "Débloquer",
        unlockWithLockIcon: "<i class='fas fa-lock'></i> Débloquer",
        myCoins: "Mes Pièces",
        secretCode: "Code secret...",
        shopMissions: "Missions",
        shopAndRewards: "Boutique & Succès",
        missionCompleted: "Terminé",
        activate: "Activer",
        achievementUnlocked: "Succès déverrouillé",
        allAchievementsUnlocked: "Tous les succès ont été déverrouillés !",
        allSongsUnlocked: "Tous les morceaux ont été débloqués !",
        incorrectCode: "Code incorrect.",
        achievement_loopMaster_title: "Maître de la boucle",
        achievement_loopMaster_desc: "Écouter 3 fois de suite le même titre en boucle.",
        achievement_retroPlayer_title: "Joueur Rétro",
        achievement_retroPlayer_desc: "Écouter 3 titres de la catégorie 'Rétro'.",
        achievement_patienceIsKey_title: "La patience est une vertu",
        achievement_patienceIsKey_desc: "Attendre la fin de la connexion WiFi 2 fois.",
        achievement_psPlayer_title: "Joueur PlayStation",
        achievement_psPlayer_desc: "Écouter 2 titres de la catégorie 'PlayStation'.",

        // Notifications & Dialogs
        titleAddedPlaylist: "Titre ajouté à votre playlist !",
        titleRemovedPlaylist: "Titre retiré de votre playlist.",
        playlistCleared: "Playlist vidée.",
        playlistSaved: "Playlist sauvegardée dans la bibliothèque !",
        unlockAvailableTitle: "Déblocage disponible !",
        unlockAvailableDesc: "Vous avez assez de pièces pour débloquer un nouveau titre exclusif.",
        updateLog: "Journal des mises à jour",
        markAsRead: "Marquer comme lu",
        trackLocked: "Ce titre est verrouillé. Débloquez-le dans la boutique d'albums !",
        youUnlocked: "Vous avez débloqué",
        allTracksUnlocked: "Tous les titres de cet album sont déjà débloqués.",
        needCoinsToUnlock: "Vous avez besoin de {COIN_COST_UNLOCK} pièces pour débloquer un titre.",
        trackToUnlock_one: "{count} titre à débloquer",
        trackToUnlock_many: "{count} titres à débloquer",

        // PWA
        pwaInstallTitle: "Installer l'application MMGEAR",
        pwaInstallDescription: "Pour une expérience optimale, installez l'application sur votre appareil. C'est rapide, léger et ne prend que peu de place.",
        pwaInstallBenefits: "Avantages :",
        pwaBenefit1: "Écoutez de la musique même avec l'écran éteint.",
        pwaBenefit2: "Accès plus rapide et direct depuis votre écran d'accueil.",
        pwaBenefit3: "Notifications pour les nouvelles sorties (prochainement).",
        pwaInstall: "Installer",
        pwaDismiss: "Plus tard",

        // Guide
        guideChoice: "Choisir un guide",
        guideMain: "1. Menu Principal",
        guideMusic: "2. Titres Musicaux",
        tutorial_main_1: "Ici, vous pouvez changer de profil entre 'Mmg Music' et 'Mmg Beats'.",
        tutorial_main_2: "Ces boutons vous permettent de revenir en arrière, d'aller à l'accueil ou de voir vos notifications.",
        tutorial_main_3: "Utilisez la barre de recherche pour trouver un titre, un album ou un tag. Le bouton à droite permet de filtrer par tags.",
        tutorial_main_9: "Changez de profil ici sur mobile.",
        tutorial_main_12: "Ceci est le lecteur principal. Il apparaît dès qu'une musique est lancée.",
        tutorial_main_13: "Cliquez sur la pochette pour voir les détails du titre ou la vidéo.",
        tutorial_main_new_1: "Bienvenue sur la MMGEAR ! Cette barre latérale est votre centre de navigation principal.",
        tutorial_main_new_2: "Le bouton 'Notifications' vous informe des nouveautés et des messages importants.",
        tutorial_main_new_3: "Naviguez entre les différentes sections du profil sélectionné.",
        tutorial_main_new_4: "Ici, vous pouvez changer le thème (clair/sombre) et accéder à ce guide à tout moment.",
        tutorial_main_new_5: "La barre du haut contient la recherche et les accès rapides.",
        tutorial_main_new_6: "Accédez rapidement à la boutique, aux succès, aux paramètres et à l'heure.",
        tutorial_main_new_7: "Le tableau de bord vous donne un aperçu rapide de tout ce qui est important.",
        tutorial_main_new_8: "Les dernières nouveautés sont présentées ici. Faites-les défiler !",
        tutorial_main_new_9: "Un aperçu de vos titres 'likés'. Cliquez pour voir la liste complète.",
        tutorial_main_new_10: "Suivez votre progression et vos activités récentes ici.",
        tutorial_main_new_11: "Contrôlez la lecture, activez le mode aléatoire ou la répétition.",
        tutorial_main_new_12: "Aimez, ajoutez à une playlist, partagez ou gérez le volume ici.",
        tutorial_main_new_13: "Cliquez sur cette poignée pour réduire ou agrandir le lecteur.",
        tutorial_music_1: "Voici une carte de titre. Cliquez dessus pour lancer la lecture.",
        tutorial_music_2: "Cliquez sur le cœur pour ajouter ce titre à vos 'Titres Likés'.",
        tutorial_music_3: "Cliquez sur le '+' pour l'ajouter à votre playlist personnelle. L'icône changera en '✓'.",
        tutorial_music_4: "Voici la page de détails. Cliquez sur la pochette pour l'agrandir.",
        tutorial_music_5: "Vous pouvez cliquer sur le nom de l'album ou sur les tags pour filtrer et découvrir d'autres contenus similaires.",
        tutorial_music_6: "Le bouton 'Ajouter à la playlist' est aussi disponible ici.",
        tutorial_music_7: "Retrouvez les liens pour écouter ce titre sur vos plateformes de streaming préférées.",
        tutorial_music_8: "S'il existe des vidéos associées (gameplay, making-of), elles apparaîtront ici.",
        tutorial_music_9: "Si l'autoplay est désactivé, vous pouvez lancer la lecture manuellement avec ce bouton.",
        tutorial_music_10: "Utilisez ces boutons pour naviguer entre les titres de l'album ou de la liste actuelle.",
        tutorial_music_11: "C'est tout pour ce guide ! Vous pouvez maintenant explorer le reste du site.",

        // Playlist & Queue
        playPlaylist: "Lancer la playlist",
        savePlaylist: "Enregistrer la playlist",
        clearPlaylist: "Vider la playlist",
        deleteFromPlaylist: "Supprimer de la playlist",
        playNext: "Lancer ensuite",
        queue: "File d'attente",
        viewMore: "Voir plus",
        addedToQueue: "ajouté à la file d'attente",
        addToQueue: "Ajouter à la file d'attente",
        removeFromQueue: "Retirer de la file d'attente",
        fromTitles: "depuis titres",
        fromMyPlaylist: "depuis ma playlist",
        fromPlaybackQueue: "depuis liste de lecture",
        fromLiked: "depuis les likes",
        fromVideos: "depuis vidéos",
        fromMmgPlaylists: "depuis Mmg Playlists",
        queueEmpty: "File d'attente vide. Clic droit (PC) ou appui long (mobile) pour ajouter.",
        nowPlayingFrom: "Lecture en cours depuis :",
        
        // Search & Filter
        searchFor: "Recherche pour",
        contentWithTag: "Contenu avec le tag",
        searchResults: "Résultats de recherche",

        // Nouveaux ajouts
        instrumentals: "Instrumentales",
        titleAndArtist: "Titre & Artiste",
        fullscreen: "Plein écran",
    },
    en: {
        // Welcome Screen
        welcomeSubtitle: "The interactive music experience.",
        bgMusic: "Background Music",
        language: "Language",
        enter: "ENTER",

        // Sidebar & Top Bar
        back: "Back",
        home: "Home",
        notifications: "Notifications",
        albums: "Albums",
        videos: "Videos",
        bonus: "Bonus",
        likedTitles: "Liked Titles",
        library: "Library",
        about: "About",
        about_mmg_music: "Mmg Music is a musical project focused on composing video game-inspired soundtracks, with influences ranging from pop to electronic music. Discover a universe rich in melodies and emotions.",
        about_mmg_beats: "Mmg Beats is the hip-hop and trap side of the project. Find hard-hitting instrumentals and productions for artists here, available on all streaming platforms.",
        guide: "Guide",
        searchPlaceholder: "Title, tag, album...",
        shop: "Shop",
        achievements: "Achievements",
        settings: "Settings",
        wifi: "WiFi",
        filterByTag: "Filter by Tag",

        // Dashboard
        suggestions: "What's New",
        recommendedPlaylists: "Recommended Playlists",
        queueTitle: "Playback Queue",
        listenNow: "Listen",
        socials: "Socials",

        // Player
        randomPlayback: "Shuffle",
        previous: "Previous",
        next: "Next",
        repeatSong: "Repeat Song",
        volume: "Volume",
        likeSong: "Like Song",
        addPlaylist: "Add to Playlist",
        shareSong: "Share Song",
        showHidePlayer: "Show/Hide Player",
        noTrackPlaying: "No track playing",
        autoplay: "Autoplay",
        autoplayOn: "Autoplay enabled",
        autoplayOff: "Autoplay disabled",
        linkCopied: "Link copied to clipboard!",
        copyFailed: "Copy failed.",

        // Cards & Sections
        titles: "Tracks",
        toggleView: "Toggle View",
        like: "Like",
        removePlaylist: "Remove from playlist",
        listenToTitle: "Listen to the track",
        viewAlbum: "View album",
        musicTitle: "Music Track",
        videoOrMakingOf: "Video / Making-Of",
        viewContent: "View content",
        workInProgress: "Content in preparation...",
        noResults: "No results found.",
        noLikedTitles: "You haven't liked any tracks yet.",
        playlistEmpty: "Your playlist is empty.",
        currentPlaylist: "My Playlist",

        // Details Page
        album: "Album",
        year: "Year",
        inspirations: "Inspirations",
        tags: "Tags",
        listenOn: "Listen on",
        launchSong: "Play Song",
        addToPlaylist: "Add to Playlist",
        addedToPlaylist: "Added to Playlist",
        gameplayVideo: "Gameplay Video",
        makingOfVideo: "Making-Of Video",
        noAssociatedVideo: "No associated video.",
        unknown: "Unknown",

        // Settings & Overlays
        sfx: "Sound Effects (SFX)",
        bgPlay: "Background Play (stable)",
        bgPlayInfo: "Enables a method to prevent music from stopping when the app is in the background on mobile. May consume slightly more battery.",
        connecting: "Connecting...",
        connectionSuccess: "Successfully connected!",
        moreOptions: "Options",
        share: "Share",

        // Shop & Achievements
        shopThemes: "Themes",
        theme_default: "Default Theme",
        theme_default_desc: "The original and clean style of the MMGEAR.",
        theme_8bit: "8-bit Theme",
        theme_8bit_desc: "A pixelated interface, just like on old consoles.",
        theme_16bit: "16-bit Theme",
        theme_16bit_desc: "A style reminiscent of the 16-bit console era.",
        theme_ps_style: "PS Style Theme",
        theme_ps_style_desc: "Inspired by the iconic PlayStation menus.",
        theme_android: "Android Theme",
        theme_android_desc: "A modern and minimalist design, Material You style.",
        shopBackgrounds: "Backgrounds",
        bg_bubbles: "Animated Bubbles",
        bg_waves: "Colored Waves",
        bg_gray: "Simple Gray",
        select: "Select",
        selected: "Selected",
        unlock: "Unlock",
        unlockWithLockIcon: "<i class='fas fa-lock'></i> Unlock",
        myCoins: "My Coins",
        secretCode: "Secret code...",
        shopMissions: "Missions",
        shopAndRewards: "Shop & Rewards",
        missionCompleted: "Completed",
        activate: "Activate",
        achievementUnlocked: "Achievement Unlocked",
        allAchievementsUnlocked: "All achievements have been unlocked!",
        allSongsUnlocked: "All songs have been unlocked!",
        incorrectCode: "Incorrect code.",
        achievement_loopMaster_title: "Loop Master",
        achievement_loopMaster_desc: "Listen to the same track 3 times in a row on loop.",
        achievement_retroPlayer_title: "Retro Player",
        achievement_retroPlayer_desc: "Listen to 3 tracks from the 'Retro' category.",
        achievement_patienceIsKey_title: "Patience is a Virtue",
        achievement_patienceIsKey_desc: "Wait for the WiFi connection to finish 2 times.",
        achievement_psPlayer_title: "PlayStation Player",
        achievement_psPlayer_desc: "Listen to 2 tracks from the 'PlayStation' category.",

        // Notifications & Dialogs
        titleAddedPlaylist: "Track added to your playlist!",
        titleRemovedPlaylist: "Track removed from your playlist.",
        playlistCleared: "Playlist cleared.",
        playlistSaved: "Playlist saved to library!",
        unlockAvailableTitle: "Unlock Available!",
        unlockAvailableDesc: "You have enough coins to unlock a new exclusive track.",
        updateLog: "Update Log",
        markAsRead: "Mark as read",
        trackLocked: "This track is locked. Unlock it in the album shop!",
        youUnlocked: "You unlocked",
        allTracksUnlocked: "All tracks in this album are already unlocked.",
        needCoinsToUnlock: "You need {COIN_COST_UNLOCK} coins to unlock a track.",
        trackToUnlock_one: "{count} track to unlock",
        trackToUnlock_many: "{count} tracks to unlock",

        // PWA
        pwaInstallTitle: "Install MMGEAR App",
        pwaInstallDescription: "For the best experience, install the app on your device. It's fast, lightweight, and takes up very little space.",
        pwaInstallBenefits: "Benefits:",
        pwaBenefit1: "Listen to music even with the screen off.",
        pwaBenefit2: "Faster and more direct access from your home screen.",
        pwaBenefit3: "Notifications for new releases (coming soon).",
        pwaInstall: "Install",
        pwaDismiss: "Later",

        // Guide
        guideChoice: "Choose a guide",
        guideMain: "1. Main Menu",
        guideMusic: "2. Music Tracks",
        tutorial_main_1: "Here, you can switch profiles between 'Mmg Music' and 'Mmg Beats'.",
        tutorial_main_2: "These buttons allow you to go back, go home, or see your notifications.",
        tutorial_main_3: "Use the search bar to find a track, album, or tag. The button on the right allows filtering by tags.",
        tutorial_main_9: "Switch profiles here on mobile.",
        tutorial_main_12: "This is the main player. It appears as soon as music is playing.",
        tutorial_main_13: "Click on the cover art to see the track details or the video.",
        tutorial_main_new_1: "Welcome to MMGEAR! This sidebar is your main navigation hub.",
        tutorial_main_new_2: "The 'Notifications' button informs you of new items and important messages.",
        tutorial_main_new_3: "Navigate between the different sections of the selected profile.",
        tutorial_main_new_4: "Here, you can change the theme (light/dark) and access this guide at any time.",
        tutorial_main_new_5: "The top bar contains the search and quick access icons.",
        tutorial_main_new_6: "Quickly access the shop, achievements, settings, and the time.",
        tutorial_main_new_7: "The dashboard gives you a quick overview of everything important.",
        tutorial_main_new_8: "The latest releases are featured here. Scroll through them!",
        tutorial_main_new_9: "A preview of your 'liked' tracks. Click to see the full list.",
        tutorial_main_new_10: "Track your progress and recent activities here.",
        tutorial_main_new_11: "Control playback, enable shuffle mode, or repeat.",
        tutorial_main_new_12: "Like, add to a playlist, share, or manage the volume here.",
        tutorial_main_new_13: "Click this handle to minimize or maximize the player.",
        tutorial_music_1: "This is a track card. Click on it to start playback.",
        tutorial_music_2: "Click the heart to add this track to your 'Liked Tracks'.",
        tutorial_music_3: "Click the '+' to add it to your personal playlist. The icon will change to a '✓'.",
        tutorial_music_4: "This is the details page. Click on the cover art to enlarge it.",
        tutorial_music_5: "You can click on the album name or tags to filter and discover other similar content.",
        tutorial_music_6: "The 'Add to Playlist' button is also available here.",
        tutorial_music_7: "Find the links to listen to this track on your favorite streaming platforms.",
        tutorial_music_8: "If there are associated videos (gameplay, making-of), they will appear here.",
        tutorial_music_9: "If autoplay is disabled, you can start playback manually with this button.",
        tutorial_music_10: "Use these buttons to navigate between tracks in the current album or list.",
        tutorial_music_11: "That's all for this guide! You can now explore the rest of the site.",

        // Playlist & Queue
        playPlaylist: "Play Playlist",
        savePlaylist: "Save Playlist",
        clearPlaylist: "Clear Playlist",
        deleteFromPlaylist: "Delete from playlist",
        playNext: "Play Next",
        queue: "Queue",
        viewMore: "View more",
        addedToQueue: "added to the queue",
        addToQueue: "Add to Queue",
        removeFromQueue: "Remove from queue",
        fromTitles: "from tracks",
        fromMyPlaylist: "from my playlist",
        fromPlaybackQueue: "from queue",
        fromLiked: "from liked songs",
        fromVideos: "from videos",
        fromMmgPlaylists: "from Mmg Playlists",
        queueEmpty: "Queue empty. Right-click (PC) or long-press (mobile) to add.",
        nowPlayingFrom: "Now playing from:",

        // Search & Filter
        searchFor: "Search for",
        contentWithTag: "Content with tag",
        searchResults: "Search Results",

        // New additions
        instrumentals: "Instrumentals",
        titleAndArtist: "Title & Artist",
        fullscreen: "Fullscreen",
    }
};
